# Generated by Django 4.2.5 on 2023-09-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre_app', '0001_initial'),
        ('author_app', '0002_author_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='genres',
            field=models.ManyToManyField(blank=True, to='genre_app.genre'),
        ),
    ]
