# Generated by Django 4.2.5 on 2023-09-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre_app', '0001_initial'),
        ('book_app', '0003_remove_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genre_app.genre'),
        ),
    ]
